# Generated by Django 6.0.6 on 2026-07-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_seed_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID (e.g., restaurant@upi)', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr_codes/'),
        ),
    ]
