# Generated by Django 6.0.6 on 2026-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_seed_upi_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_data',
            field=models.TextField(blank=True, editable=False, help_text='Base64-encoded QR code image (permanent storage)'),
        ),
    ]
