# Generated by Django 6.0.6 on 2026-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_table_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/'),
        ),
    ]
