# Generated by Django 6.0.6 on 2026-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_table_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='utrn',
            field=models.CharField(blank=True, max_length=50, verbose_name='UPI Transaction Reference'),
        ),
    ]
