# Generated by Django 6.0.6 on 2026-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_order_payment_verified_order_utrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobile Number'),
        ),
    ]
